// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/version_service.proto

package apiv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProductVersions with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProductVersions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProductVersions with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProductVersionsMultiError, or nil if none found.
func (m *ProductVersions) ValidateAll() error {
	return m.validate(true)
}

func (m *ProductVersions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_ProductVersions_Kube_Pattern.MatchString(m.GetKube()) {
		err := ProductVersionsValidationError{
			field:  "Kube",
			reason: "value does not match regex pattern \"^v?\\\\d+(?:\\\\.\\\\d+){0,2}(?:\\\\-\\\\d+)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ProductVersions_KoorOperator_Pattern.MatchString(m.GetKoorOperator()) {
		err := ProductVersionsValidationError{
			field:  "KoorOperator",
			reason: "value does not match regex pattern \"^v?\\\\d+(?:\\\\.\\\\d+){0,2}(?:\\\\-\\\\d+)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ProductVersions_Ksd_Pattern.MatchString(m.GetKsd()) {
		err := ProductVersionsValidationError{
			field:  "Ksd",
			reason: "value does not match regex pattern \"^v?\\\\d+(?:\\\\.\\\\d+){0,2}(?:\\\\-\\\\d+)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_ProductVersions_Ceph_Pattern.MatchString(m.GetCeph()) {
		err := ProductVersionsValidationError{
			field:  "Ceph",
			reason: "value does not match regex pattern \"^v?\\\\d+(?:\\\\.\\\\d+){0,2}(?:\\\\-\\\\d+)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProductVersionsMultiError(errors)
	}

	return nil
}

// ProductVersionsMultiError is an error wrapping multiple validation errors
// returned by ProductVersions.ValidateAll() if the designated constraints
// aren't met.
type ProductVersionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductVersionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductVersionsMultiError) AllErrors() []error { return m }

// ProductVersionsValidationError is the validation error returned by
// ProductVersions.Validate if the designated constraints aren't met.
type ProductVersionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductVersionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductVersionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductVersionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductVersionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductVersionsValidationError) ErrorName() string { return "ProductVersionsValidationError" }

// Error satisfies the builtin error interface
func (e ProductVersionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProductVersions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductVersionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductVersionsValidationError{}

var _ProductVersions_Kube_Pattern = regexp.MustCompile("^v?\\d+(?:\\.\\d+){0,2}(?:\\-\\d+)?$")

var _ProductVersions_KoorOperator_Pattern = regexp.MustCompile("^v?\\d+(?:\\.\\d+){0,2}(?:\\-\\d+)?$")

var _ProductVersions_Ksd_Pattern = regexp.MustCompile("^v?\\d+(?:\\.\\d+){0,2}(?:\\-\\d+)?$")

var _ProductVersions_Ceph_Pattern = regexp.MustCompile("^v?\\d+(?:\\.\\d+){0,2}(?:\\-\\d+)?$")

// Validate checks the field values on OperatorRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OperatorRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OperatorRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OperatorRequestMultiError, or nil if none found.
func (m *OperatorRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *OperatorRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVersions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OperatorRequestValidationError{
					field:  "Versions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OperatorRequestValidationError{
					field:  "Versions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVersions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OperatorRequestValidationError{
				field:  "Versions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OperatorRequestMultiError(errors)
	}

	return nil
}

// OperatorRequestMultiError is an error wrapping multiple validation errors
// returned by OperatorRequest.ValidateAll() if the designated constraints
// aren't met.
type OperatorRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OperatorRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OperatorRequestMultiError) AllErrors() []error { return m }

// OperatorRequestValidationError is the validation error returned by
// OperatorRequest.Validate if the designated constraints aren't met.
type OperatorRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OperatorRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OperatorRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OperatorRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OperatorRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OperatorRequestValidationError) ErrorName() string { return "OperatorRequestValidationError" }

// Error satisfies the builtin error interface
func (e OperatorRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOperatorRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OperatorRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OperatorRequestValidationError{}

// Validate checks the field values on DetailedVersion with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DetailedVersion) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetailedVersion with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetailedVersionMultiError, or nil if none found.
func (m *DetailedVersion) ValidateAll() error {
	return m.validate(true)
}

func (m *DetailedVersion) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_DetailedVersion_Version_Pattern.MatchString(m.GetVersion()) {
		err := DetailedVersionValidationError{
			field:  "Version",
			reason: "value does not match regex pattern \"^v?\\\\d+(?:\\\\.\\\\d+){0,2}(?:\\\\-\\\\d+)?$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if uri, err := url.Parse(m.GetImageUri()); err != nil {
		err = DetailedVersionValidationError{
			field:  "ImageUri",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := DetailedVersionValidationError{
			field:  "ImageUri",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ImageHash

	if uri, err := url.Parse(m.GetHelmRepository()); err != nil {
		err = DetailedVersionValidationError{
			field:  "HelmRepository",
			reason: "value must be a valid URI",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	} else if !uri.IsAbs() {
		err := DetailedVersionValidationError{
			field:  "HelmRepository",
			reason: "value must be absolute",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for HelmChart

	if len(errors) > 0 {
		return DetailedVersionMultiError(errors)
	}

	return nil
}

// DetailedVersionMultiError is an error wrapping multiple validation errors
// returned by DetailedVersion.ValidateAll() if the designated constraints
// aren't met.
type DetailedVersionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailedVersionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailedVersionMultiError) AllErrors() []error { return m }

// DetailedVersionValidationError is the validation error returned by
// DetailedVersion.Validate if the designated constraints aren't met.
type DetailedVersionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailedVersionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailedVersionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailedVersionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailedVersionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailedVersionValidationError) ErrorName() string { return "DetailedVersionValidationError" }

// Error satisfies the builtin error interface
func (e DetailedVersionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetailedVersion.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailedVersionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailedVersionValidationError{}

var _DetailedVersion_Version_Pattern = regexp.MustCompile("^v?\\d+(?:\\.\\d+){0,2}(?:\\-\\d+)?$")

// Validate checks the field values on DetailedProductVersions with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DetailedProductVersions) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DetailedProductVersions with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DetailedProductVersionsMultiError, or nil if none found.
func (m *DetailedProductVersions) ValidateAll() error {
	return m.validate(true)
}

func (m *DetailedProductVersions) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetKoorOperator()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "KoorOperator",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "KoorOperator",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetKoorOperator()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailedProductVersionsValidationError{
				field:  "KoorOperator",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetKsd()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "Ksd",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "Ksd",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetKsd()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailedProductVersionsValidationError{
				field:  "Ksd",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCeph()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "Ceph",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailedProductVersionsValidationError{
					field:  "Ceph",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCeph()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailedProductVersionsValidationError{
				field:  "Ceph",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DetailedProductVersionsMultiError(errors)
	}

	return nil
}

// DetailedProductVersionsMultiError is an error wrapping multiple validation
// errors returned by DetailedProductVersions.ValidateAll() if the designated
// constraints aren't met.
type DetailedProductVersionsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailedProductVersionsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailedProductVersionsMultiError) AllErrors() []error { return m }

// DetailedProductVersionsValidationError is the validation error returned by
// DetailedProductVersions.Validate if the designated constraints aren't met.
type DetailedProductVersionsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailedProductVersionsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailedProductVersionsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailedProductVersionsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailedProductVersionsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailedProductVersionsValidationError) ErrorName() string {
	return "DetailedProductVersionsValidationError"
}

// Error satisfies the builtin error interface
func (e DetailedProductVersionsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetailedProductVersions.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailedProductVersionsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailedProductVersionsValidationError{}

// Validate checks the field values on OperatorResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OperatorResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OperatorResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OperatorResponseMultiError, or nil if none found.
func (m *OperatorResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OperatorResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetVersions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OperatorResponseValidationError{
					field:  "Versions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OperatorResponseValidationError{
					field:  "Versions",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVersions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OperatorResponseValidationError{
				field:  "Versions",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OperatorResponseMultiError(errors)
	}

	return nil
}

// OperatorResponseMultiError is an error wrapping multiple validation errors
// returned by OperatorResponse.ValidateAll() if the designated constraints
// aren't met.
type OperatorResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OperatorResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OperatorResponseMultiError) AllErrors() []error { return m }

// OperatorResponseValidationError is the validation error returned by
// OperatorResponse.Validate if the designated constraints aren't met.
type OperatorResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OperatorResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OperatorResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OperatorResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OperatorResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OperatorResponseValidationError) ErrorName() string { return "OperatorResponseValidationError" }

// Error satisfies the builtin error interface
func (e OperatorResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOperatorResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OperatorResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OperatorResponseValidationError{}

// Validate checks the field values on VersionMatrix with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VersionMatrix) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VersionMatrix with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VersionMatrixMultiError, or
// nil if none found.
func (m *VersionMatrix) ValidateAll() error {
	return m.validate(true)
}

func (m *VersionMatrix) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetKoorOperator()))
		i := 0
		for key := range m.GetKoorOperator() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetKoorOperator()[key]
			_ = val

			// no validation rules for KoorOperator[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("KoorOperator[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("KoorOperator[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return VersionMatrixValidationError{
						field:  fmt.Sprintf("KoorOperator[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	{
		sorted_keys := make([]string, len(m.GetKsd()))
		i := 0
		for key := range m.GetKsd() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetKsd()[key]
			_ = val

			// no validation rules for Ksd[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("Ksd[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("Ksd[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return VersionMatrixValidationError{
						field:  fmt.Sprintf("Ksd[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	{
		sorted_keys := make([]string, len(m.GetCeph()))
		i := 0
		for key := range m.GetCeph() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetCeph()[key]
			_ = val

			// no validation rules for Ceph[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("Ceph[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, VersionMatrixValidationError{
							field:  fmt.Sprintf("Ceph[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return VersionMatrixValidationError{
						field:  fmt.Sprintf("Ceph[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return VersionMatrixMultiError(errors)
	}

	return nil
}

// VersionMatrixMultiError is an error wrapping multiple validation errors
// returned by VersionMatrix.ValidateAll() if the designated constraints
// aren't met.
type VersionMatrixMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VersionMatrixMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VersionMatrixMultiError) AllErrors() []error { return m }

// VersionMatrixValidationError is the validation error returned by
// VersionMatrix.Validate if the designated constraints aren't met.
type VersionMatrixValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VersionMatrixValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VersionMatrixValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VersionMatrixValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VersionMatrixValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VersionMatrixValidationError) ErrorName() string { return "VersionMatrixValidationError" }

// Error satisfies the builtin error interface
func (e VersionMatrixValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVersionMatrix.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VersionMatrixValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VersionMatrixValidationError{}
