//
//Copyright 2023 Koor Technologies, Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/version_service.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentVersions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kube         string `protobuf:"bytes,1,opt,name=kube,proto3" json:"kube,omitempty"`
	KoorOperator string `protobuf:"bytes,2,opt,name=koor_operator,json=koorOperator,proto3" json:"koor_operator,omitempty"`
	Ksd          string `protobuf:"bytes,3,opt,name=ksd,proto3" json:"ksd,omitempty"`
	Ceph         string `protobuf:"bytes,4,opt,name=ceph,proto3" json:"ceph,omitempty"`
}

func (x *CurrentVersions) Reset() {
	*x = CurrentVersions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentVersions) ProtoMessage() {}

func (x *CurrentVersions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentVersions.ProtoReflect.Descriptor instead.
func (*CurrentVersions) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentVersions) GetKube() string {
	if x != nil {
		return x.Kube
	}
	return ""
}

func (x *CurrentVersions) GetKoorOperator() string {
	if x != nil {
		return x.KoorOperator
	}
	return ""
}

func (x *CurrentVersions) GetKsd() string {
	if x != nil {
		return x.Ksd
	}
	return ""
}

func (x *CurrentVersions) GetCeph() string {
	if x != nil {
		return x.Ceph
	}
	return ""
}

type OperatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentVersions *CurrentVersions `protobuf:"bytes,1,opt,name=current_versions,json=currentVersions,proto3" json:"current_versions,omitempty"`
}

func (x *OperatorRequest) Reset() {
	*x = OperatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorRequest) ProtoMessage() {}

func (x *OperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorRequest.ProtoReflect.Descriptor instead.
func (*OperatorRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperatorRequest) GetCurrentVersions() *CurrentVersions {
	if x != nil {
		return x.CurrentVersions
	}
	return nil
}

type ImageVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Image   string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Hash    string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *ImageVersion) Reset() {
	*x = ImageVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVersion) ProtoMessage() {}

func (x *ImageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVersion.ProtoReflect.Descriptor instead.
func (*ImageVersion) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{2}
}

func (x *ImageVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ImageVersion) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageVersion) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type HelmVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Chart      string `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
}

func (x *HelmVersion) Reset() {
	*x = HelmVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelmVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelmVersion) ProtoMessage() {}

func (x *HelmVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelmVersion.ProtoReflect.Descriptor instead.
func (*HelmVersion) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{3}
}

func (x *HelmVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelmVersion) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *HelmVersion) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

type LatestVersions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KoorOperator *HelmVersion  `protobuf:"bytes,1,opt,name=koor_operator,json=koorOperator,proto3" json:"koor_operator,omitempty"`
	Ksd          *HelmVersion  `protobuf:"bytes,2,opt,name=ksd,proto3" json:"ksd,omitempty"`
	Ceph         *ImageVersion `protobuf:"bytes,3,opt,name=ceph,proto3" json:"ceph,omitempty"`
}

func (x *LatestVersions) Reset() {
	*x = LatestVersions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestVersions) ProtoMessage() {}

func (x *LatestVersions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestVersions.ProtoReflect.Descriptor instead.
func (*LatestVersions) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{4}
}

func (x *LatestVersions) GetKoorOperator() *HelmVersion {
	if x != nil {
		return x.KoorOperator
	}
	return nil
}

func (x *LatestVersions) GetKsd() *HelmVersion {
	if x != nil {
		return x.Ksd
	}
	return nil
}

func (x *LatestVersions) GetCeph() *ImageVersion {
	if x != nil {
		return x.Ceph
	}
	return nil
}

type OperatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestVersions *LatestVersions `protobuf:"bytes,1,opt,name=latest_versions,json=latestVersions,proto3" json:"latest_versions,omitempty"`
}

func (x *OperatorResponse) Reset() {
	*x = OperatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_version_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorResponse) ProtoMessage() {}

func (x *OperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_version_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorResponse.ProtoReflect.Descriptor instead.
func (*OperatorResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_version_service_proto_rawDescGZIP(), []int{5}
}

func (x *OperatorResponse) GetLatestVersions() *LatestVersions {
	if x != nil {
		return x.LatestVersions
	}
	return nil
}

var File_api_v1_version_service_proto protoreflect.FileDescriptor

var file_api_v1_version_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x70, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x75, 0x62,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x75, 0x62, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x6b, 0x6f, 0x6f, 0x72, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6b, 0x6f, 0x6f, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x73, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x73, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x70, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x70, 0x68, 0x22, 0x55, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x10, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0f,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x52, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x22, 0x5d, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61,
	0x72, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x0d, 0x6b, 0x6f, 0x6f, 0x72, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x6b, 0x6f, 0x6f, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x25, 0x0a, 0x03, 0x6b, 0x73, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x03, 0x6b, 0x73, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x65, 0x70, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x65, 0x70, 0x68,
	0x22, 0x53, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x51, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x94, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x42, 0x13, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x6f, 0x72, 0x2d,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02,
	0x06, 0x41, 0x70, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x06, 0x41, 0x70, 0x69, 0x5c, 0x56, 0x31,
	0xe2, 0x02, 0x12, 0x41, 0x70, 0x69, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x41, 0x70, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_version_service_proto_rawDescOnce sync.Once
	file_api_v1_version_service_proto_rawDescData = file_api_v1_version_service_proto_rawDesc
)

func file_api_v1_version_service_proto_rawDescGZIP() []byte {
	file_api_v1_version_service_proto_rawDescOnce.Do(func() {
		file_api_v1_version_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_version_service_proto_rawDescData)
	})
	return file_api_v1_version_service_proto_rawDescData
}

var file_api_v1_version_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_version_service_proto_goTypes = []interface{}{
	(*CurrentVersions)(nil),  // 0: api.v1.CurrentVersions
	(*OperatorRequest)(nil),  // 1: api.v1.OperatorRequest
	(*ImageVersion)(nil),     // 2: api.v1.ImageVersion
	(*HelmVersion)(nil),      // 3: api.v1.HelmVersion
	(*LatestVersions)(nil),   // 4: api.v1.LatestVersions
	(*OperatorResponse)(nil), // 5: api.v1.OperatorResponse
}
var file_api_v1_version_service_proto_depIdxs = []int32{
	0, // 0: api.v1.OperatorRequest.current_versions:type_name -> api.v1.CurrentVersions
	3, // 1: api.v1.LatestVersions.koor_operator:type_name -> api.v1.HelmVersion
	3, // 2: api.v1.LatestVersions.ksd:type_name -> api.v1.HelmVersion
	2, // 3: api.v1.LatestVersions.ceph:type_name -> api.v1.ImageVersion
	4, // 4: api.v1.OperatorResponse.latest_versions:type_name -> api.v1.LatestVersions
	1, // 5: api.v1.VersionService.Operator:input_type -> api.v1.OperatorRequest
	5, // 6: api.v1.VersionService.Operator:output_type -> api.v1.OperatorResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_version_service_proto_init() }
func file_api_v1_version_service_proto_init() {
	if File_api_v1_version_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_version_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentVersions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_version_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_version_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_version_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelmVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_version_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestVersions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_version_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_version_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_version_service_proto_goTypes,
		DependencyIndexes: file_api_v1_version_service_proto_depIdxs,
		MessageInfos:      file_api_v1_version_service_proto_msgTypes,
	}.Build()
	File_api_v1_version_service_proto = out.File
	file_api_v1_version_service_proto_rawDesc = nil
	file_api_v1_version_service_proto_goTypes = nil
	file_api_v1_version_service_proto_depIdxs = nil
}
