//
//Copyright 2023 Koor Technologies, Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/version_service.proto

package apiv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/koor-tech/version-service/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// VersionServiceName is the fully-qualified name of the VersionService service.
	VersionServiceName = "api.v1.VersionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VersionServiceOperatorProcedure is the fully-qualified name of the VersionService's Operator RPC.
	VersionServiceOperatorProcedure = "/api.v1.VersionService/Operator"
)

// VersionServiceClient is a client for the api.v1.VersionService service.
type VersionServiceClient interface {
	Operator(context.Context, *connect_go.Request[v1.OperatorRequest]) (*connect_go.Response[v1.OperatorResponse], error)
}

// NewVersionServiceClient constructs a client for the api.v1.VersionService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVersionServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) VersionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &versionServiceClient{
		operator: connect_go.NewClient[v1.OperatorRequest, v1.OperatorResponse](
			httpClient,
			baseURL+VersionServiceOperatorProcedure,
			opts...,
		),
	}
}

// versionServiceClient implements VersionServiceClient.
type versionServiceClient struct {
	operator *connect_go.Client[v1.OperatorRequest, v1.OperatorResponse]
}

// Operator calls api.v1.VersionService.Operator.
func (c *versionServiceClient) Operator(ctx context.Context, req *connect_go.Request[v1.OperatorRequest]) (*connect_go.Response[v1.OperatorResponse], error) {
	return c.operator.CallUnary(ctx, req)
}

// VersionServiceHandler is an implementation of the api.v1.VersionService service.
type VersionServiceHandler interface {
	Operator(context.Context, *connect_go.Request[v1.OperatorRequest]) (*connect_go.Response[v1.OperatorResponse], error)
}

// NewVersionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVersionServiceHandler(svc VersionServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	versionServiceOperatorHandler := connect_go.NewUnaryHandler(
		VersionServiceOperatorProcedure,
		svc.Operator,
		opts...,
	)
	return "/api.v1.VersionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VersionServiceOperatorProcedure:
			versionServiceOperatorHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVersionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVersionServiceHandler struct{}

func (UnimplementedVersionServiceHandler) Operator(context.Context, *connect_go.Request[v1.OperatorRequest]) (*connect_go.Response[v1.OperatorResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.v1.VersionService.Operator is not implemented"))
}
